# Generated by Django 4.1.1 on 2022-10-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customeer',
            new_name='customer',
        ),
    ]
